const SUPABASE_URL='YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY='YOUR_SUPABASE_ANON_KEY';
const app=document.getElementById('app');
const connected=!SUPABASE_URL.startsWith('YOUR_')&&!SUPABASE_ANON_KEY.startsWith('YOUR_');
let db;
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function start(){if(!connected){app.innerHTML='<main><h1>Connect Isoko Admin</h1><p>Create the Supabase project, run supabase-schema.sql, then add the Project URL and anon key to admin.js.</p></main>';return}db=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);db.auth.getSession().then(({data})=>data.session?dashboard():login())}
function login(){app.innerHTML='<main><h1>Isoko Coffee House</h1><h2>Owner Admin</h2><input id="email" type="email" placeholder="Owner email"><input id="pw" type="password" placeholder="Create password" minlength="8"><button id="create">Create account</button><button id="signin">Log in</button><p id="msg"></p></main>';document.getElementById('create').onclick=async()=>{const r=await db.auth.signUp({email:email.value.trim(),password:pw.value});msg.textContent=r.error?r.error.message:'Account created. Check email if confirmation is enabled.'};document.getElementById('signin').onclick=async()=>{const r=await db.auth.signInWithPassword({email:email.value.trim(),password:pw.value});if(r.error)msg.textContent=r.error.message;else dashboard()}}
async function dashboard(){app.innerHTML='<main><h1>Isoko Admin</h1><button id="out">Log out</button><nav><button onclick="photos()">Photos</button><button onclick="menu()">Menu</button><button onclick="settings()">Business info</button></nav><section id="content"><h2>Dashboard</h2><p>Manage Isoko photos, menu and business details.</p></section></main>';out.onclick=async()=>{await db.auth.signOut();location.reload()}}
async function photos(){const r=await db.from('gallery').select('*').order('created_at',{ascending:false});document.getElementById('content').innerHTML='<h2>Photos</h2><input id="files" type="file" accept="image/*" multiple><div id="list"></div>';files.onchange=async e=>{for(const f of e.target.files){const path=crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const u=await db.storage.from('isoko-gallery').upload(path,f);if(!u.error){const p=db.storage.from('isoko-gallery').getPublicUrl(path);await db.from('gallery').insert({storage_path:path,public_url:p.data.publicUrl})}}photos()};list.innerHTML=(r.data||[]).map(x=>'<p><img src="'+esc(x.public_url)+'" width="180"><br>'+esc(x.caption||'Isoko Coffee House')+'</p>').join('')}
async function menu(){const r=await db.from('menu_items').select('*').order('category').order('name');document.getElementById('content').innerHTML='<h2>Menu</h2>'+(r.data||[]).map(x=>'<p><input id="n'+x.id+'" value="'+esc(x.name)+'"><input id="p'+x.id+'" type="number" value="'+x.price_rwf+'"><button onclick="saveItem(\''+x.id+'\')">Save</button></p>').join('')}
window.saveItem=async id=>{await db.from('menu_items').update({name:document.getElementById('n'+id).value,price_rwf:Number(document.getElementById('p'+id).value)}).eq('id',id);menu()};
async function settings(){const r=await db.from('site_settings').select('*').eq('id',1).single();const s=r.data||{};document.getElementById('content').innerHTML='<h2>Business info</h2><input id="phone" value="'+esc(s.phone)+'"><input id="hours" value="'+esc(s.hours)+'"><input id="address" value="'+esc(s.address)+'"><input id="instagram" value="'+esc(s.instagram)+'"><button id="save">Save</button>';save.onclick=async()=>{await db.from('site_settings').update({phone:phone.value,hours:hours.value,address:address.value,instagram:instagram.value}).eq('id',1);settings()}}
start();