const API=(window.ISOKO_API_URL||localStorage.getItem('isoko_api_url')||'https://isoko-api-production.up.railway.app').replace(/\/$/,'');
const app=document.getElementById('app');
let token=localStorage.getItem('isoko_admin_token');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(path,opts={}){const h=opts.headers||{};if(token)h.Authorization='Bearer '+token;const r=await fetch(API+path,{...opts,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function page(body){app.innerHTML='<div class="wrap">'+body+'</div>'}
function login(){page('<div class="card auth"><div class="brand">ISOKO<small>COFFEE HOUSE</small></div><h1>Owner Admin</h1><p class="muted">Manage the live Isoko website.</p><label>API URL</label><input id="apiurl" value="'+esc(API)+'" placeholder="https://your-api.up.railway.app"><label>Email</label><input id="email" type="email" placeholder="Owner email"><label>Password</label><input id="password" type="password" placeholder="Password"><div class="row" style="margin-top:16px"><button class="btn primary" id="signin">Log in</button><button class="btn ghost" id="setup">Create owner</button></div><p id="msg" class="muted"></p></div>');
document.getElementById('signin').onclick=async()=>{try{localStorage.setItem('isoko_api_url',document.getElementById('apiurl').value.replace(/\/$/,''));const d=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});token=d.token;localStorage.setItem('isoko_admin_token',token);dashboard()}catch(e){msg.textContent=e.message}};
document.getElementById('setup').onclick=async()=>{try{localStorage.setItem('isoko_api_url',document.getElementById('apiurl').value.replace(/\/$/,''));await api('/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});msg.textContent='Owner created. Now log in.'}catch(e){msg.textContent=e.message}}}
function dashboard(){page('<div class="top"><div><div class="brand">ISOKO<small>COFFEE HOUSE</small></div><h1>Owner Admin</h1></div><button class="btn ghost" id="out">Log out</button></div><div class="tabs"><button class="tab" onclick="menu()">🍽️ Menu</button><button class="tab" onclick="photos()">📸 Photos</button><button class="tab" onclick="settings()">🏪 Business info</button></div><div id="content"></div>');out.onclick=()=>{localStorage.removeItem('isoko_admin_token');location.reload()};menu()}
async function menu(){try{const items=await api('/api/menu');document.getElementById('content').innerHTML='<div class="card"><div class="row"><h2>Menu</h2><button class="btn primary" onclick="addMenu()">+ Add item</button></div><p class="muted">Changes appear on the public website after its API integration is deployed.</p>'+items.map(x=>'<div class="item"><input id="c'+x.id+'" value="'+esc(x.category)+'"><input id="n'+x.id+'" value="'+esc(x.name)+'"><input id="p'+x.id+'" type="number" value="'+x.price_rwf+'"><button class="btn primary" onclick="saveItem('+x.id+')">Save</button><button class="btn danger" onclick="delItem('+x.id+')">Delete</button></div>').join('')+'</div>'}catch(e){document.getElementById('content').innerHTML='<div class="card error">'+esc(e.message)+'</div>'}}
window.addMenu=async()=>{const category=prompt('Category');const name=prompt('Item name');const price=prompt('Price in RWF');if(category&&name&&price)await api('/api/menu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category,name,price_rwf:Number(price)})});menu()};
window.saveItem=async id=>{await api('/api/menu/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:document.getElementById('c'+id).value,name:document.getElementById('n'+id).value,price_rwf:Number(document.getElementById('p'+id).value)})});menu()};
window.delItem=async id=>{if(confirm('Delete this menu item?')){await api('/api/menu/'+id,{method:'DELETE'});menu()}};
async function photos(){try{const items=await api('/api/gallery');document.getElementById('content').innerHTML='<div class="card"><h2>Photos</h2><input id="photo" type="file" accept="image/*" multiple><input id="caption" placeholder="Caption"><button class="btn primary" id="upload" style="margin-top:10px">Upload photo</button><div class="thumbs" style="margin-top:20px">'+items.map(x=>'<div class="thumb"><img src="'+API+'/api/gallery/'+x.id+'/image"><div class="cap">'+esc(x.caption||x.filename)+'<br><button class="btn danger" onclick="delPhoto('+x.id+')">Delete</button></div></div>').join('')+'</div></div>';upload.onclick=async()=>{for(const f of photo.files){const fd=new FormData();fd.append('photo',f);fd.append('caption',caption.value);await api('/api/gallery',{method:'POST',body:fd})}photos()} }catch(e){document.getElementById('content').innerHTML='<div class="card error">'+esc(e.message)+'</div>'}}
window.delPhoto=async id=>{if(confirm('Delete photo?')){await api('/api/gallery/'+id,{method:'DELETE'});photos()}};
async function settings(){const s=await api('/api/settings');document.getElementById('content').innerHTML='<div class="card"><h2>Business information</h2><label>Phone</label><input id="phone" value="'+esc(s.phone)+'"><label>Hours</label><input id="hours" value="'+esc(s.hours)+'"><label>Address</label><input id="address" value="'+esc(s.address)+'"><label>Instagram</label><input id="instagram" value="'+esc(s.instagram)+'"><button class="btn primary" id="saveSettings" style="margin-top:16px">Save changes</button><p id="saved" class="muted"></p></div>';saveSettings.onclick=async()=>{await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:phone.value,hours:hours.value,address:address.value,instagram:instagram.value})});saved.textContent='Saved.'}};
if(API&&token)api('/api/health').then(dashboard).catch(login);else login();