create extension if not exists pgcrypto;
create table if not exists public.site_settings(id integer primary key default 1,phone text not null default '+250 780 711 135',hours text not null default '05:30–00:00 daily',address text not null default 'Camp Muhoza, NM 63 St, Musanze',instagram text not null default 'https://www.instagram.com/isokocoffeehouse/',updated_at timestamptz default now());
insert into public.site_settings(id) values(1) on conflict(id) do nothing;
create table if not exists public.menu_items(id uuid primary key default gen_random_uuid(),category text not null,name text not null,price_rwf integer not null,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.gallery(id uuid primary key default gen_random_uuid(),storage_path text unique not null,public_url text not null,caption text default 'Isoko Coffee House',created_at timestamptz default now());
alter table public.site_settings enable row level security;
alter table public.menu_items enable row level security;
alter table public.gallery enable row level security;
create policy "public read settings" on public.site_settings for select using(true);
create policy "public read menu" on public.menu_items for select using(true);
create policy "public read gallery" on public.gallery for select using(true);
create policy "signed in manage settings" on public.site_settings for all to authenticated using(true) with check(true);
create policy "signed in manage menu" on public.menu_items for all to authenticated using(true) with check(true);
create policy "signed in manage gallery" on public.gallery for all to authenticated using(true) with check(true);
insert into storage.buckets(id,name,public) values('isoko-gallery','isoko-gallery',true) on conflict(id) do update set public=true;
create policy "public view isoko photos" on storage.objects for select using(bucket_id='isoko-gallery');
create policy "signed in upload isoko photos" on storage.objects for insert to authenticated with check(bucket_id='isoko-gallery');
create policy "signed in update isoko photos" on storage.objects for update to authenticated using(bucket_id='isoko-gallery') with check(bucket_id='isoko-gallery');
create policy "signed in delete isoko photos" on storage.objects for delete to authenticated using(bucket_id='isoko-gallery');